### ISSUE TITLE
Tick formatting on vertical axis (counts)

### ISSUE THREAD

**Issue by MaximMoinat** [rnugraha/react-covid19-viz#1]
Nice work Riza! Would like to try out your dashboard as my go-to COVID19 dashboard, but do have some suggestions. Maybe you have some time left to look into it. Hereby the first.

For high counts, it is hard to tell the size of the number as the counts are displayed with all the zeroes. I don't want to be counting zeroes. Would be nice to abbreviate to thousands or millions, where applicable. e.g. in screenshot below, show top tick `200k`. Also makes it easier to compare sizes between charts.

![image](https://user-images.githubusercontent.com/17825660/80988266-87bce000-8e33-11ea-887d-4ebe3e50b8ae.png)

**Comment by rnugraha** [comment]
Nice input! Thx a lot!

**Comment by MaximMoinat** [comment]
Awesome, thanks for implementing!
